/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.amf.model.AMFEvent;
import com.liferay.amf.model.AMFEventModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AMFEvent service. Represents a row in the &quot;AMFEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AMFEventModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AMFEventImpl}.
 * </p>
 *
 * @author Timothy Bell
 * @see AMFEventImpl
 * @see AMFEvent
 * @see AMFEventModel
 * @generated
 */
@ProviderType
public class AMFEventModelImpl extends BaseModelImpl<AMFEvent>
	implements AMFEventModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a amf event model instance should use the {@link AMFEvent} interface instead.
	 */
	public static final String TABLE_NAME = "AMFEvent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "amfEventId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createTime", Types.BIGINT },
			{ "type_", Types.INTEGER },
			{ "ipAddress", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("amfEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ipAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table AMFEvent (amfEventId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createTime LONG,type_ INTEGER,ipAddress VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table AMFEvent";
	public static final String ORDER_BY_JPQL = " ORDER BY amfEvent.createTime DESC";
	public static final String ORDER_BY_SQL = " ORDER BY AMFEvent.createTime DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.amf.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.amf.model.AMFEvent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.amf.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.amf.model.AMFEvent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.amf.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.amf.model.AMFEvent"),
			true);
	public static final long TYPE_COLUMN_BITMASK = 1L;
	public static final long CREATETIME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.amf.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.amf.model.AMFEvent"));

	public AMFEventModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _amfEventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAmfEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _amfEventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AMFEvent.class;
	}

	@Override
	public String getModelClassName() {
		return AMFEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("amfEventId", getAmfEventId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createTime", getCreateTime());
		attributes.put("type", getType());
		attributes.put("ipAddress", getIpAddress());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long amfEventId = (Long)attributes.get("amfEventId");

		if (amfEventId != null) {
			setAmfEventId(amfEventId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Long createTime = (Long)attributes.get("createTime");

		if (createTime != null) {
			setCreateTime(createTime);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String ipAddress = (String)attributes.get("ipAddress");

		if (ipAddress != null) {
			setIpAddress(ipAddress);
		}
	}

	@Override
	public long getAmfEventId() {
		return _amfEventId;
	}

	@Override
	public void setAmfEventId(long amfEventId) {
		_amfEventId = amfEventId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_columnBitmask = -1L;

		_createTime = createTime;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	@Override
	public String getIpAddress() {
		if (_ipAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _ipAddress;
		}
	}

	@Override
	public void setIpAddress(String ipAddress) {
		_ipAddress = ipAddress;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AMFEvent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AMFEvent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AMFEvent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AMFEventImpl amfEventImpl = new AMFEventImpl();

		amfEventImpl.setAmfEventId(getAmfEventId());
		amfEventImpl.setUserId(getUserId());
		amfEventImpl.setUserName(getUserName());
		amfEventImpl.setCreateTime(getCreateTime());
		amfEventImpl.setType(getType());
		amfEventImpl.setIpAddress(getIpAddress());

		amfEventImpl.resetOriginalValues();

		return amfEventImpl;
	}

	@Override
	public int compareTo(AMFEvent amfEvent) {
		int value = 0;

		if (getCreateTime() < amfEvent.getCreateTime()) {
			value = -1;
		}
		else if (getCreateTime() > amfEvent.getCreateTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AMFEvent)) {
			return false;
		}

		AMFEvent amfEvent = (AMFEvent)obj;

		long primaryKey = amfEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AMFEventModelImpl amfEventModelImpl = this;

		amfEventModelImpl._originalType = amfEventModelImpl._type;

		amfEventModelImpl._setOriginalType = false;

		amfEventModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AMFEvent> toCacheModel() {
		AMFEventCacheModel amfEventCacheModel = new AMFEventCacheModel();

		amfEventCacheModel.amfEventId = getAmfEventId();

		amfEventCacheModel.userId = getUserId();

		amfEventCacheModel.userName = getUserName();

		String userName = amfEventCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			amfEventCacheModel.userName = null;
		}

		amfEventCacheModel.createTime = getCreateTime();

		amfEventCacheModel.type = getType();

		amfEventCacheModel.ipAddress = getIpAddress();

		String ipAddress = amfEventCacheModel.ipAddress;

		if ((ipAddress != null) && (ipAddress.length() == 0)) {
			amfEventCacheModel.ipAddress = null;
		}

		return amfEventCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{amfEventId=");
		sb.append(getAmfEventId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createTime=");
		sb.append(getCreateTime());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", ipAddress=");
		sb.append(getIpAddress());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.amf.model.AMFEvent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>amfEventId</column-name><column-value><![CDATA[");
		sb.append(getAmfEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createTime</column-name><column-value><![CDATA[");
		sb.append(getCreateTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ipAddress</column-name><column-value><![CDATA[");
		sb.append(getIpAddress());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AMFEvent.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AMFEvent.class
		};
	private long _amfEventId;
	private long _userId;
	private String _userName;
	private long _createTime;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private String _ipAddress;
	private long _columnBitmask;
	private AMFEvent _escapedModel;
}